### ISSUE TITLE
Still broken links as Player when using wiki import?

### ISSUE THREAD

**Issue by Sonny-Crockett** [farling42/fvtt-disguise-unreachable-links#1]
I am using your module and the https://github.com/rlach/wiki-import 

When importing links and previewing from a player it seems they have the same broken link view that I do. Any ideas?

![example](https://user-images.githubusercontent.com/39606970/161622728-9040eaee-ce46-49e0-aaef-7ed103f9f4ed.png)

**Comment by farling42** [comment]
Can you show what the links look like in edit mode please.

**Comment by Sonny-Crockett** [comment]
`
Rupings were a notable @JournalEntry[reptavian]{reptavian} @JournalEntry[species]{species} native to the @JournalEntry[planet]{planet} @JournalEntry[Onderon]{Onderon}. They had vocal chords that produced a rasping roar, @JournalEntry[Limb]{finger}-like wingtips, and a thumb claw that allowed them to grasp and climb with their wings. Loyal and brave creatures, ruping were used as mounts by the @JournalEntry[Onderon rebels]{Onderon rebels} led by @Compendium[world.swaadversaries.MpmUkqc0kFFtHiRb]{Saw Gerrera} during the @JournalEntry[Onderon Civil War]{Onderon Civil War}, who equipped them with @JournalEntry[saddle]{saddles} and reins.

Behind the scenes
The ruping is named after the @JournalEntry[Star Wars: The Clone Wars]{Star Wars: The Clone Wars} concept artist @JournalEntry[Tara Rueping]{Tara Rueping}, who designed the creature.

Appearances

Sources
@JournalEntry[Star Wars: Absolutely Everything You Need to Know]{Star Wars: Absolutely Everything You Need to Know}
@JournalEntry[Star Wars: The Visual Encyclopedia]{Star Wars: The Visual Encyclopedia}
@JournalEntry[Star Wars: Absolutely Everything You Need to Know, Updated and Expanded]{Star Wars: Absolutely Everything You Need to Know, Updated and Expanded}
@JournalEntry[Star Wars: The Visual Encyclopedia]{Star Wars: The Visual Encyclopedia}
@JournalEntry[Star Wars: Absolutely Everything You Need to Know, Updated and Expanded]{Star Wars: Absolutely Everything You Need to Know, Updated and Expanded}
Notes and references
`

**Comment by farling42** [comment]
Ok, so all the links are being stored by name, rather than by id.
I will see what I can do about that.

**Comment by Sonny-Crockett** [comment]
Great, any help is appreciated!

**Comment by farling42** [comment]
If you disable the "disguise unreachable links" module, do you see the same broken links?

**Comment by Sonny-Crockett** [comment]
Yes but my issue was happening before your module, so no worries there. 

![image](https://user-images.githubusercontent.com/39606970/161625022-90e31764-6508-45ab-aa03-72f045c256e9.png)

**Comment by farling42** [comment]
So, is your request that broken links appear as normal text for players, rather than as broken links?

**Comment by Sonny-Crockett** [comment]
Yes, that is my hope. Basically, since my system does not have any real content I can buy digitally, I have to import from public and free sources and its a lot of work to clean it up from the broken links. I found your module and figure it was perfect for my issue. Thank you for even responding to me :) 

Even bigger ask would be a toggle for GMs, so they can see it normally but flip a switch to see what links they need to fix. But thats 1000% not needed, just an idea.

**Comment by farling42** [comment]
Well, I must admit that you are the first person to report an issue with the module.

And, in fact, the issue was that when I separated this code out from the Realm Works Importer module, I didn't actually do it properly. So this module never actually did anything.

I've just created 1.1, so if you do a manual update then you might see that appear, and it should work properly.

**Comment by Sonny-Crockett** [comment]
![image](https://user-images.githubusercontent.com/39606970/161631905-473f316b-f0ec-4873-a846-cb923a332e84.png)

Incredible! Thank you so much.

**Comment by farling42** [comment]
Your welcome :)
